/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Panel',
        'Ext.Button',
        'Ext.carousel.Carousel'
    ],

    config: {    	
        itemId: 'mypanel',
        layout: 'card',
        items: [
            {
                xtype: 'panel',
                height: 360,
                html: '<center><img src="./img/cat.jpg" width="70%"></center>',
                style: 'background-color:black',
                items: [
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        height: '15%',
                        itemId: 'mybutton',
                        ui: 'plain',
                        text: '<font size=6, color=white>Enter</center>'
                    },
                    {
                        xtype: 'button',
                        ui: 'plain',
                        text: '<font color=white>BPS</font>'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'mypanel2',
                items: [
                    {
                        xtype: 'carousel',
                        height: 360,
                        items: [
                            {
                                xtype: 'panel',
                                style: 'background-color:black',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        html: '<center><img src="./img/heart.png" width="80%"></center>'
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        height: 141,
                                        items: [
                                            {
                                                xtype: 'button',
                                                centered: true,
                                                docked: 'bottom',
                                                height: 68,
                                                itemId: 'mybutton2',
                                                ui: 'plain',
                                                width: 226,
                                                text: '<font size=7, color=white>Measure</font>'
                                            },
//                                            {
//                                                xtype: 'button',
//                                                itemId: 'mybutton3',
//                                                left: 125,
//                                                style: 'background-color:white',
//                                                top: 7,
//                                                ui: 'plain',
//                                                width: 100,
//                                                text: '<font color=white></font>'
//                                            }
                                            {
                                            	 xtype: 'numberfield',
                                                 height: 38,
                                                 itemId: 'mynumberfield',
                                                 left: 100,
                                                 width: 152,
                                                 label: 'Rate :',
                                                 labelWidth: '40%',
                                                 clearIcon: false,
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                style: 'background-color:white',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        ui: 'plain',
                                        text: 'Pedometer'
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        height: 122,
                                        html: '<center><img src="./img/run.png" width="43%"></center>',
                                        top: ''                                        
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        height: 201,
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'panel',
                                                height: 42,
                                                items: [
                                                    {
                                                        xtype: 'numberfield',
                                                        itemId: 'mynumberfield2',
                                                        left: '50%',
                                                        width: 177,
                                                        label: 'Calories:',
                                                        labelWidth: '50%',
                                                        clearIcon: false,
                                                    },
                                                    {
                                                        xtype: 'numberfield',
                                                        itemId: 'mynumberfield1',
                                                        width: '50%',
                                                        label: 'Steps:',
                                                        labelWidth: '45%',
                                                        clearIcon: false,
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'panel',
                                                height: 119,
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        height: 109,
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                docked: 'bottom',
                                                                height: 98,
                                                                itemId: 'mybutton6',
                                                                ui: 'plain',
                                                                width: 179,
                                                                text: '<font size=6>Start</font>'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        height: 120,
                                                        width: 103,
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                docked: 'top',
                                                                height: 117,
                                                                itemId: 'mybutton8',
                                                                ui: 'plain',
                                                                width: 180,
                                                                text: '<font size=6>Stop</font>'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                items: [
                                    {
                                        
                                        contentEl: 'htmlElement'
                                        
                                        	
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                style: 'background-color:white',
                                items: [
                                    {
                                        xtype: 'button',
                                        centered: true,
                                        height: 101,
                                        itemId: 'mybutton7',
                                        ui: 'plain',
                                        width: 188,
                                        text: '<font size=7>Exit</font>'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});